# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/raviraju/python/calci/gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import gui.resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 690)
        MainWindow.setMinimumSize(QtCore.QSize(771, 690))
        MainWindow.setMaximumSize(QtCore.QSize(771, 690))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 671))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(20, 10, 411, 17))
        self.label.setObjectName("label")
        self.btn_fr = QtWidgets.QPushButton(self.tab1)
        self.btn_fr.setGeometry(QtCore.QRect(480, 30, 101, 33))
        self.btn_fr.setObjectName("btn_fr")
        self.lb_fb = QtWidgets.QLabel(self.tab1)
        self.lb_fb.setGeometry(QtCore.QRect(20, 120, 161, 17))
        self.lb_fb.setObjectName("lb_fb")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 31, 17))
        self.label_2.setObjectName("label_2")
        self.ln_a = QtWidgets.QLineEdit(self.tab1)
        self.ln_a.setGeometry(QtCore.QRect(50, 30, 91, 33))
        self.ln_a.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_a.setObjectName("ln_a")
        self.ln_b = QtWidgets.QLineEdit(self.tab1)
        self.ln_b.setGeometry(QtCore.QRect(180, 30, 91, 33))
        self.ln_b.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_b.setObjectName("ln_b")
        self.ln_c = QtWidgets.QLineEdit(self.tab1)
        self.ln_c.setGeometry(QtCore.QRect(310, 30, 91, 33))
        self.ln_c.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_c.setObjectName("ln_c")
        self.lb_x2 = QtWidgets.QLabel(self.tab1)
        self.lb_x2.setGeometry(QtCore.QRect(590, 80, 31, 17))
        self.lb_x2.setObjectName("lb_x2")
        self.label_6 = QtWidgets.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(280, 40, 31, 17))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(150, 40, 31, 17))
        self.label_5.setObjectName("label_5")
        self.ln_info = QtWidgets.QLineEdit(self.tab1)
        self.ln_info.setGeometry(QtCore.QRect(180, 110, 551, 33))
        self.ln_info.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_info.setReadOnly(True)
        self.ln_info.setObjectName("ln_info")
        self.ln_qe = QtWidgets.QLineEdit(self.tab1)
        self.ln_qe.setGeometry(QtCore.QRect(180, 70, 221, 33))
        self.ln_qe.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_qe.setReadOnly(True)
        self.ln_qe.setObjectName("ln_qe")
        self.lb = QtWidgets.QLabel(self.tab1)
        self.lb.setGeometry(QtCore.QRect(20, 80, 161, 20))
        self.lb.setObjectName("lb")
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 81, 17))
        self.label_4.setObjectName("label_4")
        self.ln_root1 = QtWidgets.QLineEdit(self.tab1)
        self.ln_root1.setGeometry(QtCore.QRect(480, 70, 101, 33))
        self.ln_root1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_root1.setReadOnly(True)
        self.ln_root1.setObjectName("ln_root1")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(420, 80, 61, 17))
        self.label_3.setObjectName("label_3")
        self.btn_clr = QtWidgets.QPushButton(self.tab1)
        self.btn_clr.setGeometry(QtCore.QRect(630, 30, 101, 33))
        self.btn_clr.setObjectName("btn_clr")
        self.ln_root2 = QtWidgets.QLineEdit(self.tab1)
        self.ln_root2.setGeometry(QtCore.QRect(630, 70, 101, 33))
        self.ln_root2.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_root2.setReadOnly(True)
        self.ln_root2.setObjectName("ln_root2")
        self.graphicsView = GraphicsLayoutWidget(self.tab1)
        self.graphicsView.setGeometry(QtCore.QRect(20, 180, 711, 441))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.label_8 = QtWidgets.QLabel(self.tab2)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 491, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab2)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 31, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab2)
        self.label_10.setGeometry(QtCore.QRect(200, 50, 31, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab2)
        self.label_11.setGeometry(QtCore.QRect(380, 50, 31, 17))
        self.label_11.setObjectName("label_11")
        self.ln_2v_a1 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_a1.setGeometry(QtCore.QRect(60, 40, 91, 33))
        self.ln_2v_a1.setText("")
        self.ln_2v_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_a1.setObjectName("ln_2v_a1")
        self.ln_2v_b1 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_b1.setGeometry(QtCore.QRect(240, 40, 91, 33))
        self.ln_2v_b1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_b1.setObjectName("ln_2v_b1")
        self.ln_2v_c1 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_c1.setGeometry(QtCore.QRect(420, 40, 91, 33))
        self.ln_2v_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_c1.setObjectName("ln_2v_c1")
        self.ln_2v_a2 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_a2.setGeometry(QtCore.QRect(60, 80, 91, 33))
        self.ln_2v_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_a2.setObjectName("ln_2v_a2")
        self.ln_2v_b2 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_b2.setGeometry(QtCore.QRect(240, 80, 91, 33))
        self.ln_2v_b2.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_b2.setObjectName("ln_2v_b2")
        self.ln_2v_c2 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_c2.setGeometry(QtCore.QRect(420, 80, 91, 33))
        self.ln_2v_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_c2.setObjectName("ln_2v_c2")
        self.label_12 = QtWidgets.QLabel(self.tab2)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 31, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab2)
        self.label_13.setGeometry(QtCore.QRect(200, 90, 31, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab2)
        self.label_14.setGeometry(QtCore.QRect(380, 90, 31, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab2)
        self.label_15.setGeometry(QtCore.QRect(20, 130, 161, 17))
        self.label_15.setObjectName("label_15")
        self.ln_2v_eq1 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_eq1.setGeometry(QtCore.QRect(190, 120, 141, 33))
        self.ln_2v_eq1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_eq1.setReadOnly(True)
        self.ln_2v_eq1.setObjectName("ln_2v_eq1")
        self.label_16 = QtWidgets.QLabel(self.tab2)
        self.label_16.setGeometry(QtCore.QRect(340, 130, 31, 17))
        self.label_16.setObjectName("label_16")
        self.ln_2v_eq2 = QtWidgets.QLineEdit(self.tab2)
        self.ln_2v_eq2.setGeometry(QtCore.QRect(370, 120, 141, 33))
        self.ln_2v_eq2.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_2v_eq2.setReadOnly(True)
        self.ln_2v_eq2.setObjectName("ln_2v_eq2")
        self.label_17 = QtWidgets.QLabel(self.tab2)
        self.label_17.setGeometry(QtCore.QRect(520, 130, 21, 17))
        self.label_17.setObjectName("label_17")
        self.btn_fs = QtWidgets.QPushButton(self.tab2)
        self.btn_fs.setGeometry(QtCore.QRect(610, 40, 121, 33))
        self.btn_fs.setObjectName("btn_fs")
        self.btn_clr2 = QtWidgets.QPushButton(self.tab2)
        self.btn_clr2.setGeometry(QtCore.QRect(610, 80, 121, 33))
        self.btn_clr2.setObjectName("btn_clr2")
        self.label_18 = QtWidgets.QLabel(self.tab2)
        self.label_18.setGeometry(QtCore.QRect(20, 170, 81, 17))
        self.label_18.setObjectName("label_18")
        self.ln_info2 = QtWidgets.QLineEdit(self.tab2)
        self.ln_info2.setGeometry(QtCore.QRect(110, 160, 621, 33))
        self.ln_info2.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_info2.setReadOnly(True)
        self.ln_info2.setObjectName("ln_info2")
        self.graphicsView_2 = GraphicsLayoutWidget(self.tab2)
        self.graphicsView_2.setGeometry(QtCore.QRect(20, 210, 711, 411))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.ln_sol = QtWidgets.QLineEdit(self.tab2)
        self.ln_sol.setGeometry(QtCore.QRect(550, 120, 181, 33))
        self.ln_sol.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_sol.setReadOnly(True)
        self.ln_sol.setObjectName("ln_sol")
        self.tabWidget.addTab(self.tab2, "")
        self.btn_help = QtWidgets.QPushButton(self.centralWidget)
        self.btn_help.setGeometry(QtCore.QRect(468, 10, 71, 21))
        self.btn_help.setObjectName("btn_help")
        self.btn_quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_quit.setGeometry(QtCore.QRect(688, 10, 71, 21))
        self.btn_quit.setObjectName("btn_quit")
        self.btn_about = QtWidgets.QPushButton(self.centralWidget)
        self.btn_about.setGeometry(QtCore.QRect(578, 10, 71, 21))
        self.btn_about.setObjectName("btn_about")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calci"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Enter the co-efficients of quadratic equation <span style=\" font-size:11pt; color:#22840c;\">ax²+bx+c=0</span></p></body></html>"))
        self.btn_fr.setText(_translate("MainWindow", "find roots"))
        self.lb_fb.setText(_translate("MainWindow", "Feedback   :"))
        self.label_2.setText(_translate("MainWindow", "a ="))
        self.lb_x2.setText(_translate("MainWindow", ", x ="))
        self.label_6.setText(_translate("MainWindow", "c ="))
        self.label_5.setText(_translate("MainWindow", "b ="))
        self.lb.setText(_translate("MainWindow", "Roots of the given Q.E "))
        self.label_4.setText(_translate("MainWindow", "X-Y Plot      :"))
        self.label_3.setText(_translate("MainWindow", "are  x ="))
        self.btn_clr.setText(_translate("MainWindow", "clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Quadratic Equations"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Enter the co-efficients of linear equations  <span style=\" font-size:11pt; color:#1a9511;\">a</span><span style=\" font-size:11pt; color:#1a9511; vertical-align:sub;\">1</span><span style=\" font-size:11pt; color:#1a9511;\">x+b</span><span style=\" font-size:11pt; color:#1a9511; vertical-align:sub;\">1</span><span style=\" font-size:11pt; color:#1a9511;\">y = c</span><span style=\" font-size:11pt; color:#1a9511; vertical-align:sub;\">1</span>  and  <span style=\" font-size:11pt; color:#ee1166;\">a</span><span style=\" font-size:11pt; color:#ee1166; vertical-align:sub;\">2</span><span style=\" font-size:11pt; color:#ee1166;\">x+b</span><span style=\" font-size:11pt; color:#ee1166; vertical-align:sub;\">2</span><span style=\" font-size:11pt; color:#ee1166;\">y = c</span><span style=\" font-size:11pt; color:#ee1166; vertical-align:sub;\">2</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "a1 ="))
        self.label_10.setText(_translate("MainWindow", "b1 ="))
        self.label_11.setText(_translate("MainWindow", "c1 ="))
        self.label_12.setText(_translate("MainWindow", "a2 ="))
        self.label_13.setText(_translate("MainWindow", "b2 ="))
        self.label_14.setText(_translate("MainWindow", "c2 ="))
        self.label_15.setText(_translate("MainWindow", "Solution of Given L.E\'s "))
        self.label_16.setText(_translate("MainWindow", "and"))
        self.label_17.setText(_translate("MainWindow", "=>"))
        self.btn_fs.setText(_translate("MainWindow", "Find Solution"))
        self.btn_clr2.setText(_translate("MainWindow", "Clear"))
        self.label_18.setText(_translate("MainWindow", "Feedback :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Linear Equations"))
        self.btn_help.setText(_translate("MainWindow", "Help"))
        self.btn_quit.setText(_translate("MainWindow", "Quit"))
        self.btn_about.setText(_translate("MainWindow", "About"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

